/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.view;

import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import src.view.*;
import view.Fichas;

/**
 *
 * @author jaozi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        UsuarioMenu = new javax.swing.JMenu();
        Aluno = new javax.swing.JMenuItem();
        Instrutor = new javax.swing.JMenuItem();
        Aparelhos = new javax.swing.JMenu();
        aparelho = new javax.swing.JMenuItem();
        exercicios = new javax.swing.JMenu();
        Exercicio = new javax.swing.JMenuItem();
        Fichas = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Ws\\ws-netbeans\\trabalho-academia-final\\trabalho-academia-final\\images\\4165836.png")); // NOI18N
        jLabel1.setOpaque(true);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(247, 40));

        UsuarioMenu.setText("Usuário");
        UsuarioMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Aluno.setText("Aluno");
        Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoActionPerformed(evt);
            }
        });
        UsuarioMenu.add(Aluno);

        Instrutor.setText("Instrutor");
        Instrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrutorActionPerformed(evt);
            }
        });
        UsuarioMenu.add(Instrutor);

        jMenuBar1.add(UsuarioMenu);

        Aparelhos.setText("Aparelhos");
        Aparelhos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        aparelho.setText("Aparelhos");
        aparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparelhoActionPerformed(evt);
            }
        });
        Aparelhos.add(aparelho);

        jMenuBar1.add(Aparelhos);

        exercicios.setText("Exercícicos");
        exercicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Exercicio.setText("Exercícios");
        Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExercicioActionPerformed(evt);
            }
        });
        exercicios.add(Exercicio);

        jMenuBar1.add(exercicios);

        Fichas.setText("Fichas");
        Fichas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem5.setText("Adicionar ou Gerar Ficha");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Fichas.add(jMenuItem5);

        jMenuBar1.add(Fichas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoActionPerformed
        try {
            new TelaAlunos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AlunoActionPerformed

    private void InstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrutorActionPerformed
        try {
            new TelaInstrutor().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InstrutorActionPerformed

    private void aparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparelhoActionPerformed
        try {
            new TelaAparelho().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aparelhoActionPerformed

    private void ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExercicioActionPerformed
       try {
            new TelaExercicios().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExercicioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            new Fichas().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aluno;
    private javax.swing.JMenu Aparelhos;
    private javax.swing.JMenuItem Exercicio;
    private javax.swing.JMenu Fichas;
    private javax.swing.JMenuItem Instrutor;
    private javax.swing.JMenu UsuarioMenu;
    private javax.swing.JMenuItem aparelho;
    private javax.swing.JMenu exercicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
